name: laravel-vue
recipe: laravel
config:
  webroot: public
  php: '8.1'
  composer_version: 2
  database: 'mysql:8.0'
  cache: none
services:
  appserver:
    build:
      - composer install
  node:
    type: node:16
    build_internal:
      - npm install --save-exact
    command: npm run dev
    globals: {}
    port: '53241'
    ssl: false
proxy:
  node:
    - 'vite.laravel-vue.lndo.site:53241'
tooling:
  node:
    service: node
  npm:
    service: node
  npx:
    service: node

